AWSTemplateFormatVersion: 2010-09-09

Description: CloudFormation template for setting up the CAA lab 4 infrastructure

Parameters:
  rdsEndpoint:
    Type: String
    Description: The endpoint of the RDS instance
  appSG:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The security group Id for the application
  albSG:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The security group Id for the load balancer
  vpc:
    Type: AWS::EC2::VPC::Id
    Description: The VPC in which to deploy the resources
  subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The public subnets in which to deploy the resources
Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ec2ECR
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser'
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: '/'
      Roles:
        - !Ref InstanceRole
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: Lab4
      LaunchTemplateData:
        ImageId: ami-0ee415e1b8b71305f
        InstanceType: t2.micro
        SecurityGroupIds:
          - !Ref appSG
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -ex
            sudo yum -y update

            # Install Amazon Correto (AWS’s implementation of the JDK)
            sudo amazon-linux-extras enable corretto8
            sudo yum install -y java-1.8.0-amazon-corretto-devel

            # Remove the default JDK
            sudo yum remove -y java-1.7.0-openjdk

            # Download the app release artifact
            cd /home/ec2-user
            curl -L -O https://github.com/CAA-Course/app/releases/download/2022.11.2/shop-1.0.jar

            java -Dspring.profiles.active=with-form -DPOSTGRES_HOST=${rdsEndpoint} -DPOSTGRES_PORT=5432 -DPOSTGRES_USER=postgres -DPOSTGRES_PASSWORD=postgres -jar shop-1.0.jar
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: CAA-App
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: CAA-App
  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MaxSize: '1'
      MinSize: '1'
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      Tags:
        - Key: project
          PropagateAtLaunch: true
          Value: caacourse
      TargetGroupARNs:
        - !Ref TargetGroupApp
      VPCZoneIdentifier: !Ref subnets
    UpdatePolicy:
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: true
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: 'false'
      Subnets: !Ref subnets
      Scheme: internet-facing
      SecurityGroups:
        - !Ref 'albSG'
      Tags:
        - Key: project
          Value: caacourse
      Type: application
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroupApp
          Type: forward
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
  TargetGroupApp:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 8080
      Protocol: HTTP
      Tags:
        - Key: project
          Value: caacourse
      TargetType: instance
      VpcId: !Ref vpc
