AWSTemplateFormatVersion: 2010-09-09

Description: CloudFormation template for setting up the database and application instances for CAA Lab 2

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName

  AmiId:
    Description: The AMI image ID we should use to spin up the EC2 instances. Amazon Linux 2 should do it.
    Type: AWS::EC2::Image::Id

  DbIpAddress:
    Description: The private IP of the database instance
    Type: String

  DbPassword:
    Description: The password for postgres user. You can find it in the database user data
    Type: String

  AppSubnetId:
    Description: The subnet where to deploy the application
    Type: AWS::EC2::Subnet::Id

  AppSecurityGroup:
    Description: The security group Id for the application instance
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  Application:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref AmiId
      InstanceType: t2.micro
      SubnetId: !Ref AppSubnetId
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          sudo yum -y update

          # Install Amazon Correto (AWS’s implementation of the JDK)
          sudo amazon-linux-extras enable corretto8
          sudo yum install -y java-1.8.0-amazon-corretto-devel

          # Remove the default JDK
          sudo yum remove -y java-1.7.0-openjdk

          # Download the app release artifact
          cd /home/ec2-user
          curl -L -O https://github.com/CAA-Course/app/releases/download/3.0/shop-1.0.jar

          java -Dspring.profiles.active=with-form -DPOSTGRES_HOST=${DbIpAddress} -DPOSTGRES_PORT=5432 -DPOSTGRES_USER=postgres -DPOSTGRES_PASSWORD=${DbPassword} -jar shop-1.0.jar
      Tags:
        - Key: Name
          Value: App
