AWSTemplateFormatVersion: 2010-09-09

Description: CloudFormation template for setting up the application instance for CAA Lab 2

Parameters:
  AppSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The subnet where to deploy the application

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The security group for the application instance

  DbIpAddress:
    Type: String
    Description: The private IP address of the instance running the database
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})
    ConstraintDescription: must be a valid IP address of the form x.x.x.x.

Resources:
  Application:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ea0f26a6d50850c5
      InstanceType: t2.micro
      SubnetId: !Ref AppSubnetId
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          sudo yum -y update

          # Install Amazon Correto (AWS’s implementation of the JDK)
          sudo amazon-linux-extras enable corretto8
          sudo yum install -y java-1.8.0-amazon-corretto-devel

          # Remove the default JDK
          sudo yum remove -y java-1.7.0-openjdk

          # Download the app release artifact
          cd /home/ec2-user
          curl -L -O https://github.com/CAA-Course/app/releases/download/2022.11.2/shop-1.0.jar

          java -Dspring.profiles.active=with-form -DPOSTGRES_HOST=${DbIpAddress} -DPOSTGRES_PORT=5432 -DPOSTGRES_USER=postgres -DPOSTGRES_PASSWORD=caa_password123 -jar shop-1.0.jar
      Tags:
        - Key: project
          Value: caacourse
