AWSTemplateFormatVersion: 2010-09-09

Description: CloudFormation template for setting up the database and application instances for CAA Lab 2

Parameters:
  DbSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The (private) subnet where to deploy the database

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: The security group Id for the database instance

  DbImageId:
    Type: AWS::EC2::Image::Id
    Description: The image id for the database instance

Resources:
  Database:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref DbImageId
      InstanceType: t2.micro
      SubnetId: !Ref DbSubnetId
      SecurityGroupIds:
        - !Ref DbSecurityGroup
      Tags:
        - Key: project
          Value: caacourse

Outputs:
  IPAddress:
    Description: The private IP address of the instance
    Value: !GetAtt Database.PrivateIp
