AWSTemplateFormatVersion: 2010-09-09

Description: CloudFormation template for setting up the database and application instances for CAA Lab 2

Parameters:
  DbSubnetId:
    Description: The (private) subnet where to deploy the database
    Type: AWS::EC2::Subnet::Id

  DbSecurityGroup:
    Description: The security group Id for the database instance
    Type: AWS::EC2::SecurityGroup::Id

  DbImageId:
    Description: The image id for the database instance
    Type: AWS::EC2::Image::Id

  AppSubnetId:
    Description: The subnet where to deploy the application
    Type: AWS::EC2::Subnet::Id

  AppSecurityGroup:
    Description: The security group Id for the application instance
    Type: AWS::EC2::SecurityGroup::Id

Resources:
  Database:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref DbImageId
      InstanceType: t2.micro
      SubnetId: !Ref DbSubnetId
      SecurityGroupIds:
        - !Ref DbSecurityGroup
      Tags:
        - Key: project
          Value: caacourse

  Application:
    Type: AWS::EC2::Instance
    DependsOn: Database
    Properties:
      ImageId: ami-0ea0f26a6d50850c5
      InstanceType: t2.micro
      SubnetId: !Ref AppSubnetId
      SecurityGroupIds:
        - !Ref AppSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -ex
          sudo yum -y update

          # Install Amazon Correto (AWS’s implementation of the JDK)
          sudo amazon-linux-extras enable corretto8
          sudo yum install -y java-1.8.0-amazon-corretto-devel

          # Remove the default JDK
          sudo yum remove -y java-1.7.0-openjdk

          # Download the app release artifact
          cd /home/ec2-user
          curl -L -O https://github.com/CAA-Course/app/releases/download/1.0/shop-1.0.jar

          java -Dspring.profiles.active=with-form -DPOSTGRES_HOST=${Database.PrivateIp} -DPOSTGRES_PORT=5432 -DPOSTGRES_USER=postgres -DPOSTGRES_PASSWORD=caa_password123 -jar shop-1.0.jar
      Tags:
        - Key: project
          Value: caacourse
